[workspace]
members = [
	"engine",
	"ffi",
	"fuzz/bytes",
	"fuzz/raw-string",
	"fuzz/map-keys",
	"wasm",
]
resolver = "2"

[workspace.package]
authors = ["Ingvar Stepanyan <me@rreverser.com>"]
version = "0.7.0"
publish = true
edition = "2024"

[workspace.dependencies]
backtrace = "0.3"
cfg-if = "1"
cidr = { version = "0.2", features = ["serde"] }
criterion = "0.5"
fnv = "1.0.6"
getrandom = { version = "0.3" }
indoc = "2"
libc = "0.2.42"
memmem = "0.1.1"
num_enum = "0.7"
rand = "0.9"
outer-regex = { version = "1.11.1", package = "regex" }
regex-automata = { version = "0.4.9" }
serde = { version = "1.0.113", features = ["derive"] }
serde_json = "1.0.56"
sliceslice = "0.4.3"
thiserror = "1.0"
wildcard = "0.2.0"
wirefilter = { path = "engine", package = "wirefilter-engine" }

[profile.release]
panic = "unwind"
lto = true

[profile.dev]
panic = "unwind"
