[package]
authors = [ "Ingvar Stepanyan <me@rreverser.com>" ]
name = "wirefilter-engine"
version = "0.7.0"
description = "An execution engine for Wireshark-like filters"
readme = "README.md"
license = "MIT"
repository = "https://github.com/cloudflare/wirefilter"
keywords = [ "wireshark", "filter", "engine", "parser", "runtime" ]
categories = [ "config", "parser-implementations" ]
edition = "2018"

[lib]
name = "wirefilter"
bench = false

[[bench]]
name = "bench"
harness = false

[dependencies]
cfg-if = "0.1.6"
cidr = "0.1.0"
derivative = "2.1"
fnv = "1.0.6"
indexmap = { version = "1.4.0", features = ["serde-1"] }
lazy_static = "1.4.0"
memmem = "0.1.1"
rand = "0.7.3"
regex = { version = "1.3.6", optional = true }
serde = { version = "1.0.113", features = [ "derive" ] }
serde_json = "1.0.56"
sliceslice = "0.2.0"
thiserror = "1.0"
ordered-float = { version = "2.0", features = ["serde"] }

[dev-dependencies]
criterion = "0.3.3"
indoc = "0.3.6"
lazy_static = "1.1.0"

[features]
default = [ "regex" ]
