[package]
authors = ["Ingvar Stepanyan <me@rreverser.com>"]
name = "wirefilter-wasm"
version = "0.7.0"
description = "WebAssembly bindings for the Wirefilter engine"
publish = false
edition = "2018"

[lib]
crate-type = ["cdylib"]
# Avoid duplicate compilation error messages as we don't have doctests anyway
doctest = false

[dependencies]
js-sys = "0.3.5"
wasm-bindgen = { version = "0.2.28", features = ["serde-serialize"] }
wirefilter-engine = { path = "../engine", default-features = false }
